version: '3'
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/usr/src/app/django_app  # Adjust the source path
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    environment:
      - DEBUG=True
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - my_network  # Assign the Django service to the same network as elasticsearch

  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
        - "9200:9200"
    networks:
      - my_network  # Assign the Elasticsearch service to the same network as django

networks:
  my_network:
