name: Django Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unit testing
      run: |
        python manage.py test
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report